#!/bin/bash
pgrep -x dmenu && exit

declare -A mapping=( ["portainer"]=9000 ["qbittorrent"]=9001 ["plex"]=32400 ["sonarr"]=8989 ["radarr"]=7878 ["nextcloud"]=8081 ["organizr"]=80 \
    ["jackett"]=9117 ["ombi"]=3579 ["lazylibrarian"]=5299 ["lidarr"]=8686)

choice=$(echo -e "portainer\nqbittorrent\nplex\nsonarr\nradarr\nnextcloud\norganizr\njackett\nombi\nlazylibrarian\nlidarr" | rofi -dmenu -p "server app")

if [ ! -z $choice ]; then
    port=${mapping[$choice]}
    firefox 192.168.1.105:$port
fi
