#!/bin/sh

copied_link=$(xclip -o)
prompt="do you want to run getbooks with copied links: $copied_link"
choice=$(echo -e "yes\nno" | dmenu -i -p "$prompt")
case "$choice" in
    'yes')
        getbooks $1
        ;;
    'no')
        exit 0
esac

